// <auto-generated />
using System;
using Almacen_X_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Almacen_X_.Migrations.Empleado
{
    [DbContext(typeof(EmpleadoContext))]
    [Migration("20200217032910_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Almacen_X_.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Cedula")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Codigo_Empleado")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("DateTime");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("varchar(30)");

                    b.HasKey("EmpleadoID");

                    b.ToTable("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
